### DISCUSSION TITLE
consistent failure in GitVersion increment in ADO using v3 of the extension with gitversion 6.0.X

### DISCUSSION THREAD

**Discussion by RolfMoleman** [GitTools/actions#1390] [Q&A]
Hi, I'm a bit confused by this one. 

we have had GitVersion 5.x in our subtree based repository template for sometime but its behaviour has been inconsistent. Working on a fix, i opted to upgrade to v3 of the extensions and v6.0.x of GitVersion.

GitVersion setup behaves entirely as expected but GitVersion increment returns the following:

``` shell
##[debug]Evaluating condition for step: 'Increment Gitversion'
##[debug]Evaluating: and(succeededOrFailed(), eq('prod', 'prod'))
##[debug]Evaluating and:
##[debug]..Evaluating succeededOrFailed:
##[debug]..=> True
##[debug]..Evaluating eq:
##[debug]....Evaluating String:
##[debug]....=> 'prod'
##[debug]....Evaluating String:
##[debug]....=> 'prod'
##[debug]..=> True
##[debug]=> True
##[debug]Expanded: and(True, eq('prod', 'prod'))
##[debug]Result: True
Starting: Increment Gitversion
==============================================================================
Task         : Execute GitVersion Task
Description  : Easy Semantic Versioning (https://semver.org/) for projects using Git
Version      : 3.0.4
Author       : GitTools Contributors
Help         : See the [documentation](https://gitversion.net/docs/) for help
==============================================================================
##[debug]Using node path: /home/vsts/agents/3.248.0/externals/node20_1/bin/node
Running on: 'Azure Pipelines'
##[debug]Disabling telemetry
Disable Telemetry
##[debug]Processed: ##vso[task.setvariable variable=DOTNET_CLI_TELEMETRY_OPTOUT;isOutput=false;issecret=false;]true
##[debug]Processed: ##vso[task.setvariable variable=DOTNET_NOLOGO;isOutput=false;issecret=false;]true
##[debug]getVariable - INPUT_TARGETPATH:
```

the extension is configured in my pipeline as:

```yml
- task: gitversion/execute@3
   condition: and(succeededOrFailed(), eq('${{ environment_tag }}', 'prod'))
   displayName: "Increment Gitversion"
   enabled: true
   name: "gitversion_increment"
   inputs:
      UseConfigFile: true
      ConfigFilePath: "$(System.DefaultWorkingDirectory)/$(repo_name)/.config/GitVersion.yml"
      #targetPath: $(System.DefaultWorkingDirectory)/$(repo_name)/
```

The repo_name variable refers to the name of my actual repository, this is used as we utilise terraofmr modules which we checkout to a relative path. All checkouts are non shallow. 

My GitVersion.yml is configured as:

```yml
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
assembly-informational-format: "{InformationalVersion}"
mode: ContinuousDelivery
tag-prefix: "[vV]"
continuous-delivery-fallback-tag: ""
next-version: 1.0.0
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
tag-pre-release-weight: 60000
commit-message-incrementing: Enabled
branches:
  renovate:
    regex: ^(renovate)[/-]
    mode: ContinuousDeployment
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
    is-source-branch-for: ["main"]
    is-mainline: false
    source-branches: ["main"]

  main:
    mode: ContinuousDelivery
    tag: ""
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches:
      - develop
      - release
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 55000
  develop:
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    source-branches: []
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 0
  release:
    mode: ContinuousDeployment
    tag: beta
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches:
      - develop
      - main
      - bug
      - release
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
    pre-release-weight: 30000
  feature:
    mode: ContinuousDeployment
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    source-branches:
      - develop
      - main
      - release
      - feature
      - bug
      - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  pull-request:
    mode: ContinuousDeployment
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
    source-branches:
      - develop
      - main
      - release
      - feature
      - bug
      - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  hotfix:
    mode: ContinuousDeployment
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    source-branches:
      - develop
      - main
      - support
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  bug:
    mode: ContinuousDeployment
    tag: ""
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^bug?[/-]
    source-branches:
      - main
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 55000
  documentation:
    mode: ContinuousDeployment
    tag: ""
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^(docs|documentation)[/-]
    source-branches:
      - main
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
increment: Inherit
merge-message-formats: {}
update-build-number: true
```

my repo structure is

```txt
|   .gitignore
|   .pre-commit-config.yaml
|   .prettierignore
|   README.md
|   TERRAFORM.md
|   tree.txt
|   
+---.assets
|       ascii-art.txt
|       documentation.png
|       home.png
|       Logo.ansi.txt
|       logo.png
|       pipeline-screenshot.png
|       quality.png
|       screenshot.png
|       teams.png
|       terraform.png
|       
+---.azuredevops
|   |   module_repos.yml
|   |   project_specific_variables.yml
|   |   repo_template-updater.yml
|   |   
|   \---PULL_REQUEST_TEMPLATE
|       |   PULL_REQUEST_TEMPLATE.md
|       |   
|       \---branches
|               DOCUMENTATION.md
|               FEATURE.md
|               FIX.md
|               RELEASE.md
|               
+---.config
|       .ci-readme-terraform-docs.yml
|       .ci-terraform-docs.yml
|       .cspell.json
|       .docs-terraform-terraform-docs.yml
|       .readme-terraform-docs.yml
|       .terraform-terraform-docs.yml
|       .tfdir-readme-terraform-docs.yml
|       GitVersion.yml
|       IDE-config.txt
|       terraform-default_values.json
|       
+---.github
|       renovate.json
|       
+---.pre-commit_logs
|       .gitkeep
|       
+---docs
|   |   .order
|   |   documentation.md
|   |   terraform.md
|   |   
|   \---terraform
|           .order
|           TERRAFORM.md
|           tf_footer.txt
|           tf_header.txt
|           
+---iac_arm
|       blank_arm_template.json
|       
+---iac_terraform
|   |   .tflint.hcl
|   |   data.tf
|   |   main.tf
|   |   modules.tf
|   |   outputs.tf
|   |   README.md
|   |   TERRAFORM.md
|   |   variables.tf
|   |   versions.tf
|   |   
|   \---environment
|       |   default.tfvars
|       |   
|       +---dev
|       |       variables.tfvars
|       |       
|       +---poc
|       |       variables.tfvars
|       |       
|       +---prod
|       |       variables.tfvars
|       |       
|       \---uat
|               variables.tfvars
|               
\---repo_template
    |   .gitattributes
    |   .gitignore
    |   .pre-commit-config.yaml
    |   .prettierignore
    |   CODE_OF_CONDUCT.md
    |   LICENCE.md
    |   README.md
    |   TERRAFORM.md
    |   
    +---.assets
    |       ascii-art.txt
    |       documentation.png
    |       home.png
    |       Logo.ansi.txt
    |       logo.png
    |       pipeline-screenshot.png
    |       quality.png
    |       screenshot.png
    |       teams.png
    |       terraform.png
    |       
    +---.config
    |       .ci-readme-terraform-docs.yml
    |       .ci-terraform-docs.yml
    |       .cspell.json
    |       .docs-terraform-terraform-docs.yml
    |       .mega-linter.yml
    |       .readme-terraform-docs.yml
    |       .terraform-terraform-docs.yml
    |       .tfdir-readme-terraform-docs.yml
    |       GitVersion.yml
    |       terraform-default_values.json
    |       
    +---.github
    |   |   release.yml
    |   |   renovate.json
    |   |   
    |   +---ISSUE_TEMPLATE
    |   |       00_bug_report.yml
    |   |       01_documentation.yml
    |   |       02_feature_request.yml
    |   |       03_repository.yml
    |   |       04_other.yml
    |   |       config.yml
    |   |       
    |   +---PULL_REQUEST_TEMPLATE
    |   |       DOCUMENTATION.md
    |   |       FEATURE.md
    |   |       FIX.md
    |   |       PULL_REQUEST_TEMPLATE.md
    |   |       RELEASE.md
    |   |       
    |   \---workflows
    |           Board_Updater.yml
    |           pullrequest.yml
    |           release.yml
    |           scheduled_maintenance.yml
    |           secret_syncer.yml
    |           
    +---.paste-at-repo-root
    |   |   .gitignore
    |   |   .pre-commit-config.yaml
    |   |   .prettierignore
    |   |   README.md
    |   |   
    |   +---.assets
    |   |       ascii-art.txt
    |   |       documentation.png
    |   |       home.png
    |   |       Logo.ansi.txt
    |   |       logo.png
    |   |       pipeline-screenshot.png
    |   |       quality.png
    |   |       screenshot.png
    |   |       teams.png
    |   |       terraform.png
    |   |       
    |   +---.azuredevops
    |   |   |   module_repos.yml
    |   |   |   project_specific_variables.yml
    |   |   |   repo_template-updater.yml
    |   |   |   
    |   |   \---PULL_REQUEST_TEMPLATE
    |   |       |   PULL_REQUEST_TEMPLATE.md
    |   |       |   
    |   |       \---branches
    |   |               DOCUMENTATION.md
    |   |               FEATURE.md
    |   |               FIX.md
    |   |               RELEASE.md
    |   |               
    |   +---.config
    |   |       .checkov.baseline
    |   |       .ci-readme-terraform-docs.yml
    |   |       .ci-terraform-docs.yml
    |   |       .cspell.json
    |   |       .docs-terraform-terraform-docs.yml
    |   |       .readme-terraform-docs.yml
    |   |       .terraform-terraform-docs.yml
    |   |       .tfdir-readme-terraform-docs.yml
    |   |       GitVersion.yml
    |   |       IDE-config.txt
    |   |       terraform-default_values.json
    |   |       
    |   +---.github
    |   |       renovate.json
    |   |       
    |   +---.pre-commit_logs
    |   |       .gitkeep
    |   |       
    |   +---docs
    |   |   |   .order
    |   |   |   documentation.md
    |   |   |   terraform.md
    |   |   |   
    |   |   \---terraform
    |   |           .order
    |   |           TERRAFORM.md
    |   |           tf_footer.txt
    |   |           tf_header.txt
    |   |           
    |   +---iac_arm
    |   |       blank_arm_template.json
    |   |       
    |   \---iac_terraform
    |       |   .tflint.hcl
    |       |   data.tf
    |       |   main.tf
    |       |   modules.tf
    |       |   outputs.tf
    |       |   README.md
    |       |   variables.tf
    |       |   versions.tf
    |       |   
    |       \---environment
    |           |   default.tfvars
    |           |   
    |           +---dev
    |           |       variables.tfvars
    |           |       
    |           +---poc
    |           |       variables.tfvars
    |           |       
    |           +---prod
    |           |       variables.tfvars
    |           |       
    |           \---uat
    |                   variables.tfvars
    |                   
    +---.pre-commit_logs
    |       .gitkeep
    |       
    +---build
    |   +---pipelines
    |   |   |   infrastructure.yml
    |   |   |   
    |   |   +---build_templates
    |   |   |       maven.yml
    |   |   |       
    |   |   +---code_quality_templates
    |   |   |       infracost.yml
    |   |   |       megalinter.yml
    |   |   |       mend_bolt.yml
    |   |   |       owasp.yml
    |   |   |       terraform_docs.yml
    |   |   |       
    |   |   +---iac_templates
    |   |   |       terraform_apply.yml
    |   |   |       terraform_destroy.yml
    |   |   |       terraform_plan.yml
    |   |   |       variables.yml
    |   |   |       
    |   |   +---maven
    |   |   |       code_quality-maven.yml
    |   |   |       dependency_updater-maven.yml
    |   |   |       infrastructure_quality-maven.yml
    |   |   |       mega_linter-maven.yml
    |   |   |       
    |   |   +---release_templates
    |   |   |       create_git_tag.yml
    |   |   |       
    |   |   \---whitelist_templates
    |   |           whitelist_clean.yml
    |   |           whitelist_prepare.yml
    |   |           
    |   \---scripts
    |           get_tf_version.ps1
    |           Manage_whitelist.ps1
    |           pull_request_comment_generic.ps1
    |           pull_request_comment_terraform.ps1
    |           pull_request_creator.ps1
    |           repo_template-lastCommit.ps1
    |           retain_build.ps1
    |           terraform_variable_case_azure_pipeline.ps1
    |           
    \---docs
        |   .order
        |   code_quality.md
        |   documentation.md
        |   terraform.md
        |   UPGRADE_GUIDE.md
        |   USAGE_GUIDE.md
        |   
        +---code_quality
        |       .order
        |       infracost.md
        |       megalinter.md
        |       mend_bolt.md
        |       mend_renovate.md
        |       owasp.md
        |       
        +---reports
        |       infracost-precommit-terraform-dev.json
        |       
        \---terraform
                .order
                TERRAFORM.md
                terraform_docs.md
                tf_footer.txt
                tf_header.txt
```
