### DISCUSSION TITLE
Support `/diag` and `/verbosity` in the `Execute` action

### DISCUSSION THREAD

**Discussion by TaffarelJr** [GitTools/actions#1653] [Ideas]
Lately the GitVersion `Execute` action has been erroring out a lot in our GitHub workflows -- but it never outputs the exception details. All we get is `undefined` for the JSON output, and a blocked build.

To facilitate debugging, what would it take to add the following optional input parameters to the `Execute` action, each resulting in the described changes to the command-line switches:

| Input Parameter | Type | Description | Required | Default | Result|
|:--- |:---:|:--- |:---:|:--- |:--- |
| `enableDiagnositcs` | bool |Whether to run GitVersion with additional diagnostic information | `false` | `'false'` | determines whether to add the `/diag` switch or not |
| `verbosity` | string | Specifies the amount of information to be displayed<br/><br/>[ Quiet \| Minimal \| Normal \| Verbose \| Diagnostic ] | `false` | `'Normal'` | `/verbosity` switch is always added to the command-line (for transparency), but is either set to the default value or to whatever the user configures |

Command-line switch reference: https://gitversion.net/docs/usage/cli/arguments

**Comment by johnrappelepam** [comment]
We solved this by using the "command" option: 

With this:
```
- task: gitversion-command@4.4.2 
  displayName: 'Generate Build Version'
  name: version_step # step id used as a reference for output values
  inputs:
    arguments: '/output buildserver /verbosity minimal /l console /config ./GitVersion.yml'
```

The "buildserver" output automatically sets the build number in ADO, but it is optional, considering your question.
