### ISSUE TITLE
Running GitVersion twice (in separate runs) yields incorrect build names

### ISSUE THREAD

**Issue by basilfx** [GitTools/actions#1016]
Using Azure DevOps, my typical template starts with:

```yaml
name: $(Build.Repository.Name) $(GitVersion.FullSemVer)
```

This gets updated correctly by the GitVersion step, which I invoke as follows:

```yaml
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: Determine version
  inputs:
    useConfigFile: true
    configFilePath: common/GitVersion.releaseFlow.yml
```

The build logs confirms that the name gets update correctly:

```
Starting: Determine version
...
Async Command Start: Update Build Number
>> Update build number to My.Service 1.2.3 for build 82737 <<
Async Command End: Update Build Number
Finishing: Determine version
```

If, for some reason, I need to retry a build (e.g. due to transient network errors), the second attempt generates an incorrect build name:

```
Starting: Determine version
...
Async Command Start: Update Build Number
>> Update build number to 40.4.0 for build 82737 <<
Async Command End: Update Build Number
Finishing: Determine version
```

Note how the `My.Service` part (the repository name in the `name` part at the start of the template) is discarded. That should not happen.
