### ISSUE TITLE
Version not incrementing since update to version 5.x

### ISSUE THREAD

**Issue by saisworld** [GitTools/actions#1040]
Hi, I have recently upgraded to Gitools version 5.x from GitVersion, 

Prior to the upgrade, my version count 11.3.x, since it was upgraded it got reset and went back to 1.0.0. So I have update the "next-version" in the Gitversion.yaml to "12.0.0" to have the baseline. It picked up the version correctly and after merging into master branch it set the version to "12.0.0". However, when I create a new branch from master and started pushing changes into the new branch (features/zzz) it didnt increment the minor, instead it again created versions with 12.0.0-aplha1. Please advise if there is a misconfiguration in my pipeline or gitversion.yaml files?

Below is my pipeline configuration 

```
    - task: gitversion/setup@0
      inputs:
        versionSpec: '5.x'
        preferLatestVersion: true

    - task: gitversion/execute@0
      inputs:
        useConfigFile: true
        configFilePath: 'GitVersion.yml'
        updateAssemblyInfo: true

```

GitVersion.yaml -

```
mode: Mainline
next-version: 12.0.0
assembly-versioning-scheme: MajorMinorPatch
increment: Inherit
branches:
    feature:
        regex: ^feature(s)?[/-]
        tag: alpha
        increment: Inherit
        source-branches: [ 'develop', 'main', 'release', 'feature', 'master', 'hotfix' ]        
    master:
        tag: ''
ignore:
  sha: []
merge-message-formats: {}
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
commit-message-incrementing: MergeMessageOnly
```
