### ISSUE TITLE
[ISSUE]: Git shallow copy check fails

### ISSUE THREAD

**Issue by Codelet** [GitTools/actions#1089]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

GitHub Actions

### What are you seeing?

After this change https://github.com/GitTools/actions/pull/1070 GitVersion GH action started to fail.
I assume git command is missing the working directory info there.

### What is expected?

I expect it not to fail

### Steps to Reproduce

- Checkout code using checkout@v4 action
- Use GitVersion setup action
- Use GitVersion execute action

### Output log or link to your CI build (if appropriate).

```shell
Run gittools/actions/gitversion/execute@v0
  with:
    targetPath: /home/runner/work/MyRepo/MyRepo/repo
    useConfigFile: true
    configFilePath: /home/runner/work/MyRepo/MyRepo/repo/build/GitVersion.yml
    disableCache: false
    disableNormalization: false
    updateAssemblyInfo: false
  env:
    DOTNET_ROOT: /usr/share/dotnet
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_NOLOGO: true
Agent: 'GitHub Actions'
Command: git rev-parse --is-shallow-repository
/usr/bin/git rev-parse --is-shallow-repository
fatal: not a git repository (or any of the parent directories): .git
Error: Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by Codelet** [comment]
It is not easy to post whole workflow as it is spread between several shared composite actions
Your example is using v1.0.0 and I am using v0.
It is something like this if I virtually glue my composite actions together:
```
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.checkout-path }}
        fetch-depth: 0
          
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
        preferLatestVersion: true

    - name: Determine version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        targetPath: ${{ inputs.checkout-path }}
        useConfigFile: true
        configFilePath: ${{ inputs.checkout-path }}${{ inputs.config-file-path }}/GitVersion.yml
```
