### ISSUE TITLE
[ISSUE]: unsupported extension name extensions.worktreeconfig

### ISSUE THREAD

**Issue by pascalgulikers** [GitTools/actions#1090]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

GitHub Actions

### What are you seeing?

```
Run gittools/actions/gitversion/execute@v0
  with:
    disableCache: false
    disableNormalization: false
    useConfigFile: false
    configFilePath: GitVersion.yml
    updateAssemblyInfo: false
    
Agent: 'GitHub Actions'
Command: git rev-parse --is-shallow-repository
/usr/bin/git rev-parse --is-shallow-repository
false
Command: dotnet-gitversion /home/ubuntu/_work/***/*** /output json /output buildserver
/home/ubuntu/_work/_tool/GitVersion.Tool/5.12.0/x64/dotnet-gitversion /home/ubuntu/_work/***/*** /output json /output buildserver
INFO [03/12/24 12:04:45:30] Working directory: /home/ubuntu/_work/***/***
unsupported extension name extensions.worktreeconfig
INFO [03/12/24 12:04:45:33] Done writing 
Error: Error: The process '/home/ubuntu/_work/_tool/GitVersion.Tool/5.12.0/x64/dotnet-gitversion' failed with exit code 1
```

### What is expected?

To continue instead of halt.
```
/usr/bin/git version
  git version 2.34.1
```

### Steps to Reproduce

It worked until now, so it probably was introduced in a recent commit

**Comment by pascalgulikers** [comment]
I was already afraid you were gonna ask, but unfortunately I can't, because it's part of a huge reusable workflow which I can't publicly share, but the gitversion part are these two actions:

```
- name: Install GitVersion if required
  if: inputs.useGitVersion == 'true'
  uses: gittools/actions/gitversion/setup@v0
  with:
    versionSpec: 5.x
    preferLatestVersion: true

- name: Determine package version with GitVersion
  if: inputs.useGitVersion == 'true'
  id: determine_git_version
  uses: gittools/actions/gitversion/execute@v0
```
It worked before [PR 1070](https://github.com/GitTools/actions/pull/1070) was merged
I suspect this line: https://github.com/GitTools/actions/pull/1070/files#diff-f25d460f91bbf4450dd61cb84d2b9024daf6510591ee38db94b276624d423bddR27

where the shallow-check was introduced, maybe another version of git is being executed instead of the one in /usr/bin?

**Comment by pascalgulikers** [comment]
```
- name: Checkout Test GitHub repository
  if: inputs.selfTest == true
  uses: actions/checkout@v4
  with:
    repository: ${{ inputs.selfTestRepo }}
    ref: ${{ inputs.selfTestBranch }}
    token: ${{ env.CUSTOM_TOKEN }}
```
As you can see, in this case it's checking out other repos than the one where the workflow is running, pretty exotic scenario perhaps..
Furthermore I can confirm that `gittools/actions/gitversion/execute@v0.13.4` works as expected, so this is a workaround for now

**Comment by olibanjoli** [comment]
we're having the same problems

also tried @main:

```
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@main
        with:
          versionSpec: 5.x
          preferLatestVersion: true

      - name: Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@main
        with:
          useConfigFile: true
```

**Comment by pascalgulikers** [comment]
The hotfix seams to work:

```
Run gittools/actions/gitversion/execute@main
Agent: 'GitHub Actions'
Command: git -C /home/ubuntu/_work/***/*** rev-parse --is-shallow-repository
/usr/bin/git -C /home/ubuntu/_work/***/*** rev-parse --is-shallow-repository
false
Command: dotnet-gitversion /home/ubuntu/_work/***/*** /output json /output buildserver
/home/ubuntu/_work/_tool/GitVersion.Tool/5.12.0/x64/dotnet-gitversion /home/ubuntu/_work/***/*** /output json /output buildserver
INFO [03/12/24 13:46:50:83] Working directory: /home/ubuntu/_work/***/***
```

**Comment by olibanjoli** [comment]
it does not work, still the same error:


```
Run gittools/actions/gitversion/execute@main
  with:
    disableShallowCloneCheck: true
    useConfigFile: true
    disableCache: false
    disableNormalization: false
    configFilePath: GitVersion.yml
    updateAssemblyInfo: false
  env:
    DOTNET_INSTALL_DIR: /home/runner/dotnet
    DOTNET_ROOT: /home/runner/dotnet
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_NOLOGO: true
Agent: 'GitHub Actions'
Command: dotnet-gitversion /actions-runner/_work/***p/***p /output json /output buildserver /config GitVersion.yml
/actions-runner/_work/_tool/GitVersion.Tool/5.1[2](https://github.com/x/actions/runs/8277673615/job/22648456590#step:5:2).0/x64/dotnet-gitversion /actions-runner/_work/***p/***p/output json /output buildserver /config GitVersion.yml
INFO [0[3](https://github.com/p/p/actions/runs/8277673615/job/22648456590#step:5:3)/1[4](https://github.com/x/p/actions/runs/8277673615/job/22648456590#step:5:4)/24 8:31:[5](https://github.com/p/x/actions/runs/8277673615/job/22648456590#step:5:5)0:82] Working directory: /actions-runner/_work/***p/***p
unsupported extension name extensions.worktreeconfig
INFO [03/14/24 8:31:50:85] Done writing 
Error: Error: The process '/actions-runner/_work/_tool/GitVersion.Tool/5.12.0/x[6](https://github.com/p/p/actions/runs/8277673615/job/22648456590#step:5:6)4/dotnet-gitversion' failed with exit code 1
```

**Comment by olibanjoli** [comment]
```yaml
name: test

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "/home/runner/dotnet"
    strategy:
      matrix:
        service:
          - foo
          - bar
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@main
        with:
          versionSpec: 5.x
          preferLatestVersion: true

      - name: Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@main
        with:
          disableShallowCloneCheck: true
          useConfigFile: true
```

**Comment by pascalgulikers** [comment]
The error is suddenly back:
```
Run actions/checkout@v4
  with:
    fetch-depth: 0
    fetch-tags: true
    repository: ***/***
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    show-progress: true
    lfs: false
    submodules: false
    set-safe-directory: true

/usr/bin/git version
  git version 2.34.1

Run gittools/actions/gitversion/setup@v1
  with:
    versionSpec: 5.x
    preferLatestVersion: true
    includePrerelease: false
    ignoreFailedSources: false

Run gittools/actions/gitversion/execute@v1
  with:
    disableShallowCloneCheck: true
    useConfigFile: false
    disableCache: false
    disableNormalization: false
    configFilePath: GitVersion.yml
    updateAssemblyInfo: false
```

Resulting in:

```
INFO [04/22/24 15:49:41:90] Working directory: /home/ubuntu/_work/***/***
unsupported extension name extensions.worktreeconfig
INFO [04/22/24 15:49:41:95] Done writing 
Error: Error: The process '/home/ubuntu/_work/_tool/GitVersion.Tool/5.12.0/x64/dotnet-gitversion' failed with exit code 1
```
