### ISSUE TITLE
[ISSUE]: GitHub Actions - gitreleasemanager/addasset@v1.1.1 action.yml references milestone over tagName

### ISSUE THREAD

**Issue by BlairMcClelland** [GitTools/actions#1137]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

GitHub Actions

### What are you seeing?

When using addasset@v1.1.1 in Github Actions I am seeing intellisense errors in VSC due to action.yml referencing milestone when I think it should reference tagName instead?

https://github.com/GitTools/actions/blob/main/gitreleasemanager/addasset/action.yml#L23

![image](https://github.com/GitTools/actions/assets/95189768/ac729f16-77da-4c92-8bb7-0d810700d827)

Adding it anyway works okay but throws a warning as shown

![image](https://github.com/GitTools/actions/assets/95189768/8a34db0e-ca65-40f9-8ce0-cd7b76fd64c0)

Note that initially when using milestone only I got this error 
> GitReleaseManager 0.17.0+98dca9b37825946960194db5258e7fea6f1900e4
Copyright (c) 2015 - Present - GitTools Contributors
ERROR(S):
  Required option 't, tagName' is missing.

### What is expected?

GHA intellisense recognises tagName as a required argument and thus doesn't flag a warning in the workflow run

### Steps to Reproduce

```
    - name: Add asset to a release
      uses: gittools/actions/gitreleasemanager/addasset@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: ${{ github.repository_owner }}
        repository: ${{ github.event.repository.name }}
        milestone: 'v1.0.1'
        tagName: 'v1.0.1'
        assets: tool_${{ matrix.configuration }}_${{ env.GitVersion_FullSemVer }}.zip 
```

### Output log or link to your CI build (if appropriate).

> Warning: Unexpected input(s) 'tagName', valid inputs are ['owner', 'repository', 'token', 'milestone', 'assets', 'targetDirectory']
Run gittools/actions/gitreleasemanager/addasset@v1.1.1
  with:
    token: ***
    owner: org
    repository: repo
    milestone: v1.0.1
    tagName: v1.0.1
    assets: D:\a\tool\tool/tool_Release_1.0.2
