### ISSUE TITLE
[ISSUE]: actions v2 does not allow GRM 0.18.0

### ISSUE THREAD

**Issue by mkevenaar** [GitTools/actions#1184]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

GitHub Actions

### What are you seeing?

![image](https://github.com/user-attachments/assets/c885d56e-4ef6-4690-8a72-c41b4f563e5c)
I am trying to install 0.18.0, as described in [versions.md](https://github.com/GitTools/actions/blob/main/docs/versions.md) but it's not allowed

### What is expected?

Action to work and install GRM version 0.18.0

### Steps to Reproduce

```
      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@v2.0.0
        with:
          versionSpec: '0.18.x'
```
