### ISSUE TITLE
git branch --create-reflog suggestion fails on master branch

### ISSUE THREAD

**Issue by casz** [GitTools/actions#12]
The suggestion in the readme fails on master branch

```yml
    - name: Fetch tags and master for GitVersion
    run: |
        git fetch --tags
        git branch --create-reflog master origin/master
```
