### ISSUE TITLE
[ISSUE]: GitReleaseManager GithubAction not logging to job

### ISSUE THREAD

**Issue by Stepami** [GitTools/actions#1224]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitReleaseManager package

GitHub Actions

### What are you seeing?

https://github.com/Stepami/hydrascript/actions/runs/10360139446/job/28678471915

In GitHub Actions logs i see no logs of tool.

But if i run it locally logs appear:
![image](https://github.com/user-attachments/assets/83980963-20ff-4e68-93d9-580895720355)
![image](https://github.com/user-attachments/assets/a8efc4dc-2282-436f-bd63-b65a896a35ea)

### What is expected?

logging to GitHub Actions Console

### Steps to Reproduce

```yml
name: Release Workflow

on:
  push:
    branches:
      - 'release'
      
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    outputs: 
      determined_version: ${{ steps.version_step.outputs.majorMinorPatch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '5.12.0'
      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true
      - name: Setup GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@v3.0.0
        with:
          versionSpec: '0.18.x'
      - name: Create release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/create@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: 'Stepami'
          repository: 'hydrascript'
          milestone: 'v${{ steps.version_step.outputs.majorMinorPatch }}'
          name: 'v${{ steps.version_step.outputs.majorMinorPatch }}'
```
