### ISSUE TITLE
$(Patch) not being populated in Azure DevOps

### ISSUE THREAD

**Issue by TabithaLarkin** [GitTools/actions#124]
Since the most recent update, the $(Patch) variable is not being populated, or is being populated as an empty string, when running the task on a new branch. It has also occurred by merging master into an existing branch, and then running that through the pipeline.

The value is being calculated by GitVersion:
```
Executing GenerateBuildLogOutput for 'AzurePipelines'.
{
  "Major":4,
  "Minor":6,
  "Patch":0,
...
```

Referring to it, however does not work:
```yaml
- task: PowerShell@2
  displayName: Get-Version
  enabled: true
  inputs:
    targetType: 'filepath'
    filePath: 'build/Scripts/Get-Version.ps1'
    arguments: -Verbose `
     -GitVersionMajor $(Major) `
     -GitVersionMinor $(Minor) `
     -GitVersionPatch $(Patch) `
...
```

```
C:\agent\_work\149\s\build\Scripts\Get-Version.ps1' -Verbose ` -GitVersionMajor 4 ` -GitVersionMinor 6 ` -GitVersionPatch  ` ...
```
