### ISSUE TITLE
AssemblyInfoFilename file not found

### ISSUE THREAD

**Issue by mrbiggred** [GitTools/actions#125]
When I try to update the AssemblyInfo.cs files by setting the `updateAssemblyInfo: true` I get the following error:

```
 AssemblyInfoFilename file not found at 
```

Might be related to this [issue](https://github.com/GitTools/GitVersion/issues/2225) on the GitVersion repo.

You can view the error in action at:

https://github.com/saturdaymp/XPlugins.iOS.BEMCheckBox/runs/710150101?check_suite_focus=true

To reproduce:

1) Create a GitHub workflow file with the following:

```yml
name: CI
on: [push]

jobs:
  build:
    name: Build Job
    runs-on: macos-latest
    defaults:
      run:
        working-directory: Source

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history for GitVersion
        run: git fetch --prune --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.3
        with:
          versionSpec: '5.3.4'

      - name: Generate Version Info using GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.3
        with: 
          updateAssemblyInfo: true
      
      - name: Display GitVersion values
        run: |
          echo "Major: ${{ steps.gitversion.outputs.major }}"
          echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          echo "Patch: ${{ steps.gitversion.outputs.patch }}"
```

2) When run the following error message is displayed:

```
Run gittools/actions/gitversion/execute@v0.9.3
  with:
    updateAssemblyInfo: true
    useConfigFile: false
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
##[error]Error: AssemblyInfoFilename file not found at 
```

**Comment by BertelBB** [comment]
I had the same issue and I solved it by giving a relative path to the `AssemblyInfo.cs` file, using the `updateAssemblyInfoFilename` variable.

```
...
    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.3
      with:
        updateAssemblyInfo: true
        updateAssemblyInfoFilename: ./src/SampleService/Properties/AssemblyInfo.cs
...
```
