### ISSUE TITLE
[ISSUE]: Error in DevOps Pipeline: The current operating system is not capable of running this task

### ISSUE THREAD

**Issue by philried24** [GitTools/actions#1300]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### What are you seeing?

I installed the Azure DevOps extension and wanted to test the tasks in my pipeline. The integration is set up as follows:
```
      - task: gitversion/execute@3.0.0
        displayName: Determine `Version`
```

However, after starting the pipeline, I encountered the following error:
The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

We primarily use Linux as our operating system, but I also tried running it on Windows, and I’m still getting the same error.

### What is expected?

I expected that the GitVersion tool would be installed and ready to use, but at this point, I’m unsure if the extension is working as intended.

### Steps to Reproduce

```
jobs:
  - job: Overall
    workspace:
      clean: all
    pool:
      name: linux
      demands:
        - Agent.OS -equals Linux
        - docker
        - general
    variables:
      - group: devops
    steps:
      - checkout: self
        fetchDepth: 0
        fetchTags: true
        persistCredentials: true
      - task: gitversion/execute@3.0.0
        displayName: Determine Version
```
As mentioned earlier, the error occurs on both Linux and Windows.
