### ISSUE TITLE
[ISSUE]: GitTools 3.0.3 not working with Gitea 1.22.4 and Gitea Runner

### ISSUE THREAD

**Issue by DanielBock73** [GitTools/actions#1377]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

GitHub Actions

### What are you seeing?

I'm experiencing issues with GitTools version 3.0.3 when used with Gitea 1.22.4 and a Gitea Runner. The setup is no longer functioning correctly. The last version of GitTools that works in this environment is 1.2.0.

**Environment**
- GitTools version: 3.0.3
- Gitea version: 1.22.4
- Using Gitea Runner

### What is expected?

GitTools should work correctly with the current Gitea setup.

### Steps to Reproduce

1. Set up Gitea 1.22.4 with Gitea Runner
2. Install GitTools 3.0.3
3. Attempt to use GitTools in the Gitea environment

### Output log or link to your CI build (if appropriate).

```shell
Running on: 'GitHub Actions'
Disable Telemetry
Executing GitVersion
Command: git -C /workspace/fdt121/Bock.Fdt121.Core.Registry rev-parse --is-shallow-repository
Command: /opt/hostedtoolcache/GitVersion.Tool/5.12.0/dotnet-gitversion /workspace/fdt121/Bock.Fdt121.Core.Registry /output json /output buildserver
::error::Command failed: /opt/hostedtoolcache/GitVersion.Tool/5.12.0/dotnet-gitversion /workspace/fdt121/Bock.Fdt121.Core.Registry /output json /output buildserver%0A/bin/sh: 1: /opt/hostedtoolcache/GitVersion.Tool/5.12.0/dotnet-gitversion: not found%0A
```

**Comment by DanielBock73** [comment]
Add additional info an image of the error log:
![Image](https://github.com/user-attachments/assets/0dfeb258-1732-4d73-beb1-064a357686df)

**Comment by arturcic** [comment]
@DanielBock73 these tasks/actions are meant to be used in GitHub Actions and Azure Pipelines, it's not supported on Gitea, so closing

**Comment by JinxedDev** [comment]
While Gitea is not supported it does work, for anyone that is interested in using it here is an example that works for me with Gitea version: 1.23.4

```
name: Git Version Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history for all branches and tags
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # SDK Version to use; x will use the latest version of the 3.1 channel
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '5.12.0 '

      - name: Calculate Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true
```
