### ISSUE TITLE
updateAssemblyInfo does not work as expected

### ISSUE THREAD

**Issue by giuliov** [GitTools/actions#14]
In my build script I set the `updateAssemblyInfo` parameter to `true` but the AssemblyInfo.cs files keep the original value.

Source example:
https://github.com/tfsaggregator/aggregator-cli/blob/d25e1b8284d958c786ac7116f816da7e5fa011f2/.github/workflows/release-to-GitHub.yml#L26-L30

Log
```
Run gittools/actions/execute-gitversion@v0.3
  with:
    updateAssemblyInfo: true
    useConfigFile: false
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_ROOT: ../share/dotnet
/opt/hostedtoolcache/GitVersion.Tool/5.1.3/x64/dotnet-gitversion /home/runner/work/aggregator-cli/aggregator-cli /output json 
```
