### ISSUE TITLE
[ISSUE]: GitVersion Tool Cannot Find a Usable Version of libssl

### ISSUE THREAD

**Issue by Elias504** [GitTools/actions#1429]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

GitHub Actions

### What are you seeing?

GitVersion cannot seem to find the appropriate version of libssl to complete installation on runner machines. Regardless of the version I use, it does not seem to find one that is compatible. Below is a log of the issue.

```
Run gittools/actions/gitversion/setup@v3.1.1
  with:
    versionSpec: 6.0.x
    includePrerelease: false
    ignoreFailedSources: false
    preferLatestVersion: false
  env:
    DOTNET_ROOT: /usr/share/dotnet
Running on: 'GitHub Actions'
Disable Telemetry
--------------------------
Acquiring GitVersion.Tool for version spec: 6.0.x
--------------------------
Querying tool versions for GitVersion.Tool@6.0.x 
Found matching version: 6.0.5
Looking for local tool GitVersion.Tool@6.0.5
Directory /opt/hostedtoolcache/GitVersion.Tool/6.0.5 not found
Command: dotnet tool install GitVersion.Tool --tool-path /home/runner/work/_temp/40fea6[2](https://github.com/kualatechzm/orange-book-engine/actions/runs/12620433626/job/35166126045?pr=215#step:4:2)2-200e-45f[3](https://github.com/kualatechzm/orange-book-engine/actions/runs/12620433626/job/35166126045?pr=215#step:4:3)-95b1-e10fd3593370 --version 6.0.5
Error: No usable version of libssl was found
Aborted (core dumped)
```

### What is expected?

The installation of GitVersion for use on runner machine.

### Steps to Reproduce

Running the following actions should yield the same error. 
```
  calculate-version:
    name: 🔥 Get GitVersion
    runs-on: ubuntu-latest
    needs: prepare
    if: github.event_name == 'push' && needs.prepare.outputs.head_tag == ''
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}
      sha: ${{ steps.gitversion.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5

      - name: ⬇ Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: 6.0.x

      - name: 💻 Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.1
        with:
          useConfigFile: true
```

The above yaml was running perfectly fine a few months ago. Having re-run actions that had already passed and now fail should show this.

### Output log or link to your CI build (if appropriate).

```shell
Run gittools/actions/gitversion/setup@v3.1.1
  with:
    versionSpec: 6.0.x
    includePrerelease: false
    ignoreFailedSources: false
    preferLatestVersion: false
  env:
    DOTNET_ROOT: /usr/share/dotnet
Running on: 'GitHub Actions'
Disable Telemetry
--------------------------
Acquiring GitVersion.Tool for version spec: 6.0.x
--------------------------
Querying tool versions for GitVersion.Tool@6.0.x 
Found matching version: 6.0.5
Looking for local tool GitVersion.Tool@6.0.5
Directory /opt/hostedtoolcache/GitVersion.Tool/6.0.5 not found
Command: dotnet tool install GitVersion.Tool --tool-path /home/runner/work/_temp/40fea6[2](https://github.com/kualatechzm/orange-book-engine/actions/runs/12620433626/job/35166126045?pr=215#step:4:2)2-200e-45f[3](https://github.com/kualatechzm/orange-book-engine/actions/runs/12620433626/job/35166126045?pr=215#step:4:3)-95b1-e10fd3593370 --version 6.0.5
Error: No usable version of libssl was found
Aborted (core dumped)
```
