### ISSUE TITLE
[ISSUE]: `gitrealeasemanager/create` does not include `targetcommitish` and `inputFilePath` parameters

### ISSUE THREAD

**Issue by TaffarelJr** [GitTools/actions#1432]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

GitHub Actions

### What are you seeing?

When using the `gitreleasemanager/create` action, there are parameters defined for `targetcommitish` and `inputFilePath`; however, upon execution, those parameters are not included in the command line sent to `dotnet-gitreleasemanager`.

Sample GitHub Action:
```yml
- uses: gittools/actions/gitreleasemanager/create@v3
  with:
    owner: ${{ github.repository_owner }}
    token: ${{ secrets.GITHUB_TOKEN }}
    repository: my-repo
    targetDirectory: ${{ github.workspace }}
    targetcommitish: ${{ github.sha }}              # <-- property is valid
    name: v${{ steps.gitversion.outputs.semVer }}
    inputFilePath: ReleaseNotes.md                  # <-- property is valid
```

Command-line generated from the above Action (wrapped for readability):
```bash
/opt/hostedtoolcache/GitReleaseManager.Tool/0.18.0/dotnet-gitreleasemanager create
  --owner my-org
  --token ***
  --repository my-repo
  --targetDirectory /home/runner/work/my-repo/my-repo
  --name v1.2.3
```
_( `--targetcommitish` and `--inputFilePath` command-line parameters left out)_

### What is expected?

`--targetcommitish` and `--inputFilePath` command-line parameters should be included, as specified in the Action:
```bash
/opt/hostedtoolcache/GitReleaseManager.Tool/0.18.0/dotnet-gitreleasemanager create
  --owner my-org
  --token ***
  --repository my-repo
  --targetDirectory /home/runner/work/my-repo/my-repo
  --targetcommitish edf8f64259dca665f01c1da5fff9650b7e342b69
  --name v1.2.3
  --inputFilePath ReelaseNotes.md
```

### Steps to Reproduce

Include the `targetcommitish` and `inputFilePath` parameters in a GitHub Action,
and observe the corresponding `--targetcommitish` and `--inputFilePath` command-line parameters are not generated.

### Output log or link to your CI build (if appropriate).

```shell

```
