### ISSUE TITLE
[ISSUE]: Input parameter configFilePath ignored in gitversion/execute@3.2.0

### ISSUE THREAD

**Issue by freakalot** [GitTools/actions#1570]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### What are you seeing?

I created a task in my pipeline which looks like this: 

```yaml
- task: gitversion/execute@3.2.0
    displayName: Determine Version and update Assembly Infos
    inputs:
      configFilePath: '$(Build.SourcesDirectory)/${{parameters.configPath}}'
      updateAssemblyInfo: true
    env: 
      uniqueVersionNumber: ${{ parameters.uniqueVersionNumber }}
```

and another task using the command action:
```yaml
- task: gitversion/command@3.2.0
    displayName: Determine Version and write wixfile
    inputs:
      arguments: '/config ${{parameters.configPath}} /updatewixversionfile'
    env: 
      uniqueVersionNumber: ${{ parameters.uniqueVersionNumber }}
```

When running the pipeline, the call for the command action looks fine:
```
Command: C:\agent\_work\_tool\GitVersion.Tool\5.12.0\dotnet-gitversion.exe --roll-forward Major C:\agent\_work\1916\s /config NugetPackages/SMS.CommonNative/GitVersion.yml /updatewixversionfile
```

but the call for the execute action entirely ignores the input parameter for the config file:
```
Command: C:\agent\_work\_tool\GitVersion.Tool\5.12.0\dotnet-gitversion.exe --roll-forward Major C:\agent\_work\1916\s /output json /l console /updateassemblyinfo
```

### What is expected?

the config file selected in the configFilePath input parameter is properly used when executing the pipeline

### Steps to Reproduce

see above comment

### Output log or link to your CI build (if appropriate).

```shell

```
