### ISSUE TITLE
Azure DevOps GitVersion does not work with non-standard branch names

### ISSUE THREAD

**Issue by mthamil** [GitTools/actions#170]
My company uses `main` as the name of the master branch and the gitversion execute task fails with the message: `Could not find a 'develop' or 'master' branch, neither locally nor remotely.`

I also tried:
```yaml
    task: gitversion/execute@0 
      displayName: "Run gitversion"
      inputs:
        additionalArguments:
          branches:
            master:
              regex: ^main$
```

but that failed.
