### ISSUE TITLE
gitversion/execute does not work with multi-repo checkout and a custom working directory

### ISSUE THREAD

**Issue by mthamil** [GitTools/actions#172]
I have a shared `GitVersion.yml` to use in a build template, so I have two checkout tasks: one to check out the repo with the config file, and the other to check out the repo to be built.
This creates a directory structure like so:
```
    d:/a/1/s/
        CurrentRepo
        TemplateRepo
```

My `gitversion/execute` task is like the following:
```yml
    - task: gitversion/execute@0 
      displayName: "Run gitversion"
      inputs:
         targetPath: '$(Build.SourcesDirectory)/CurrentRepo'
         useConfigFile: true
         configFilePath: '$(Build.SourcesDirectory)/TemplateRepo/GitVersion.yml'
```

Using this `targetPath` results in a doubled up path like `d:/a/1/s/d:/a/1/s/CurrentRepo` and the `.git` directory cannot be found. This is due to the path join [here](https://github.com/GitTools/actions/blob/cadfeb7381b9c1caf750e4ae4bf65de3e6f6f596/src/tools/gitversion/tool.ts#L51).

If I set `targetPath` to a relative directory such as `./CurrentRepo`, it fails because the directory cannot be found.

As it is, I cannot see a way that this feature will work because of the discrepancy between the directory existence check and the joined path.
