### ISSUE TITLE
Tags not fetched in GitHub actions when following documentation

### ISSUE THREAD

**Issue by roryprimrose** [GitTools/actions#176]
I have the following in my github actions which is copied from the documentation in the readme (with config added).

```
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.4
      with:
          versionSpec: '5.2.x'
    
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.4
      with:
        useConfigFile: true
        configFilePath: ./GitVersion.yml
```

Running the fetch step gives the following in the logs.

```
Run git fetch --prune --unshallow
  git fetch --prune --unshallow
  shell: /bin/bash -e {0}
  env:
    projectName: ModelBuilder
```

This isn't downloading the tags as expected and therefore generating an incorrect version.

I have updated the step to explicitly include tags.

```
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow --tags
```

The build now fetches the following tags and generates the correct version.

```
Run git fetch --prune --unshallow --tags
  git fetch --prune --unshallow --tags
  shell: /bin/bash -e {0}
  env:
    projectName: ModelBuilder
From https://github.com/roryprimrose/ModelBuilder
 * [new branch]      master         -> origin/master
 * [new tag]         4.0.0-beta0049 -> 4.0.0-beta0049
 * [new tag]         4.0.0-beta0050 -> 4.0.0-beta0050
 * [new tag]         4.0.0-beta0051 -> 4.0.0-beta0051
 * [new tag]         4.0.0-beta0052 -> 4.0.0-beta0052
 * [new tag]         4.0.0-beta0053 -> 4.0.0-beta0053
 * [new tag]         4.0.0-beta0054 -> 4.0.0-beta0054
 * [new tag]         4.0.0-beta0057 -> 4.0.0-beta0057
 * [new tag]         4.0.0-beta0059 -> 4.0.0-beta0059
 * [new tag]         6.0.0          -> 6.0.0
 * [new tag]         6.0.0-beta0001 -> 6.0.0-beta0001
 * [new tag]         6.0.0-beta0002 -> 6.0.0-beta0002
 * [new tag]         6.0.0-beta0003 -> 6.0.0-beta0003
 * [new tag]         6.0.0-beta0004 -> 6.0.0-beta0004
 * [new tag]         6.0.0-beta0005 -> 6.0.0-beta0005
 * [new tag]         6.0.0-beta0006 -> 6.0.0-beta0006
 * [new tag]         6.0.0-beta0007 -> 6.0.0-beta0007
 * [new tag]         6.0.0-beta0008 -> 6.0.0-beta0008
 * [new tag]         6.0.0-beta0009 -> 6.0.0-beta0009
 * [new tag]         6.0.0-beta0010 -> 6.0.0-beta0010
 * [new tag]         6.0.0-beta0011 -> 6.0.0-beta0011
[truncated]
```

The documentation on [unshallow](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---unshallow) isn't clear about what it does with tags but it does not seem to fetch them.

**Comment by roryprimrose** [comment]
What's weird is that on another repo tags are fetched.

```
Run git fetch --prune --unshallow
From https://github.com/roryprimrose/Neovolve.CodeAnalysis.ChangeTracking
 * [new branch]      dependabot/nuget/Microsoft.NET.Test.Sdk-16.7.0 -> origin/dependabot/nuget/Microsoft.NET.Test.Sdk-16.7.0
 * [new branch]      master         -> origin/master
 * [new tag]         0.1.0-beta0031 -> 0.1.0-beta0031
 * [new tag]         0.1.0-18-isvisible0019     -> 0.1.0-18-isvisible0019
 * [new tag]         0.1.0-beta0013             -> 0.1.0-beta0013
 * [new tag]         0.1.0-beta0014             -> 0.1.0-beta0014
 * [new tag]         0.1.0-beta0021             -> 0.1.0-beta0021
 * [new tag]         0.1.0-beta0026             -> 0.1.0-beta0026
 * [new tag]         0.1.0-beta0030             -> 0.1.0-beta0030
 * [new tag]         0.1.0-beta0044             -> 0.1.0-beta0044
 * [new tag]         0.1.0-beta0047             -> 0.1.0-beta0047
 * [new tag]         0.1.0-beta0065             -> 0.1.0-beta0065
 * [new tag]         0.1.0-beta0069             -> 0.1.0-beta0069
 * [new tag]         0.1.0-beta0084             -> 0.1.0-beta0084
 * [new tag]         0.1.0-beta0104             -> 0.1.0-beta0104
 * [new tag]         0.1.0-pullrequest0022-0020 -> 0.1.0-pullrequest0022-0020
```

**Comment by asbjornu** [comment]
The documentation was changed in #207 to use `fetch-depth: 0` instead. That should according to GitHub's own documentation fetch all history for all branches and tags. Does that work?

```yaml
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
```
