### ISSUE TITLE
Unrecognized value "steps"

### ISSUE THREAD

**Issue by kleinpetr** [GitTools/actions#209]
When I try to use azure tasks from an example I have got this error

```
stages:
  - stage: gitversion
    # condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop')))
    jobs:
      - job: gitversion
        steps:
          - task: gitversion/setup@0
            displayName: Install GitVersion
            inputs:
              versionSpec: "5.1.3"
          - task: gitversion/execute@0
            displayName: Use GitVersion
          - script: |
              echo FullSemVer: $(fullSemVer)
              echo ##vso[build.updatebuildnumber]$(fullSemVer)
              echo Major: ${{ steps.gitversion.outputs.major }}
              echo Minor: ${{ steps.gitversion.outputs.minor }}
              echo Patch: ${{ steps.gitversion.outputs.patch }}
              echo PreReleaseTag: ${{ steps.gitversion.outputs.preReleaseTag }}
              echo PreReleaseTagWithDash: ${{ steps.gitversion.outputs.preReleaseTagWithDash }}
              echo PreReleaseLabel: ${{ steps.gitversion.outputs.preReleaseLabel }}
              echo PreReleaseNumber: ${{ steps.gitversion.outputs.preReleaseNumber }}
              echo WeightedPreReleaseNumber: ${{ steps.gitversion.outputs.weightedPreReleaseNumber }}
              echo BuildMetaData: ${{ steps.gitversion.outputs.buildMetaData }}
              echo BuildMetaDataPadded: ${{ steps.gitversion.outputs.buildMetaDataPadded }}
              echo FullBuildMetaData: ${{ steps.gitversion.outputs.fullBuildMetaData }}
              echo MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}
              echo SemVer: ${{ steps.gitversion.outputs.semVer }}
              echo LegacySemVer: ${{ steps.gitversion.outputs.legacySemVer }}
              echo LegacySemVerPadded: ${{ steps.gitversion.outputs.legacySemVerPadded }}
              echo AssemblySemVer: ${{ steps.gitversion.outputs.assemblySemVer }}
              echo AssemblySemFileVer: ${{ steps.gitversion.outputs.assemblySemFileVer }}
              echo InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}
              echo BranchName: ${{ steps.gitversion.outputs.branchName }}
              echo Sha: ${{ steps.gitversion.outputs.sha }}
              echo ShortSha: ${{ steps.gitversion.outputs.shortSha }}
              echo NuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
              echo NuGetVersion: ${{ steps.gitversion.outputs.nuGetVersion }}
              echo NuGetPreReleaseTagV2: ${{ steps.gitversion.outputs.nuGetPreReleaseTagV2 }}
              echo NuGetPreReleaseTag: ${{ steps.gitversion.outputs.nuGetPreReleaseTag }}
              echo VersionSourceSha: ${{ steps.gitversion.outputs.versionSourceSha }}
              echo CommitsSinceVersionSource: ${{ steps.gitversion.outputs.commitsSinceVersionSource }}
              echo CommitsSinceVersionSourcePadded: ${{ steps.gitversion.outputs.commitsSinceVersionSourcePadded }}
              echo CommitDate: ${{ steps.gitversion.outputs.commitDate }}
```

`/azure-pipelines.yml (Line: 35, Col: 21): Unrecognized value: 'steps'. Located at position 853 within expression: format('echo FullSemVer: $(fullSemVer) echo ##vso[build.updatebuildnumber]$(fullSemVer) echo Major: {0} echo Minor: {1} echo Patch: {2} echo PreReleaseTag: {3} echo PreReleaseTagWithDash: {4} echo PreReleaseLabel: {5} echo PreReleaseNumber: {6} echo WeightedPreReleaseNumber: {7} echo BuildMetaData: {8} echo BuildMetaDataPadded: {9} echo FullBuildMetaData: {10} echo MajorMinorPatch: {[...]`

So how can I access to output from @execute task?

**Comment by roryprimrose** [comment]
The `##` in `echo ##vso[build.updatebuildnumber]$(fullSemVer)` is probably stuffing you up because `#` is a comment marker in yaml. 

I had a similar issue a while ago and the only way I could [get it to work was a bit of a hack](https://www.neovolve.com/2019/05/03/gitversion-and-github-with-azure-devops-build-yaml/). I'd like to see a better solution.

**Comment by chlumper** [comment]
I have the very same issue! Removing the first two echo lines with `$(fullSemVer)` doesn't resolve the issue, so I it's most probably not about the `#`.
```
Encountered error(s) while parsing pipeline YAML:
/azure-pipelines-version-test.yml (Line: 21, Col: 13): Unrecognized value: 'steps'. Located at position 772 within expression: format('echo Major: {0}
echo Minor: {1}
echo Patch: {2}
echo PreReleaseTag: {3}
echo PreReleaseTagWithDash: {4}
echo PreReleaseLabel: {5}
echo PreReleaseNumber: {6}
echo WeightedPreReleaseNumber: {7}
echo BuildMetaData: {8}
echo BuildMetaDataPadded: {9}
echo FullBuildMetaData: {10}
echo MajorMinorPatch: {11}
echo SemVer: {12}
echo LegacySemVer: {13}
echo LegacySemVerPadd[...]
```
GitTools version `0.9.4.2007081356` on AzureDevOps

**Comment by chlumper** [comment]
I was able to get it working with the following format to reference the output variables (please be aware of the upper case variable names).
<details>
<summary>Config (without fallbacks)</summary>

```
steps:
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.1.3'
- task: gitversion/execute@0
  displayName: Use GitVersion
- script: |
    echo FullSemVer: $(FULLSEMVER)
    echo ##vso[build.updatebuildnumber]$(FULLSEMVER)
    echo Major: $(MAJOR)
    echo Minor: $(MINOR)
    echo Patch: $(PATCH)
    echo PreReleaseTag: $(PRERELEASETAG)
    echo PreReleaseTagWithDash: $(PRERELEASETAGWITHDASH)
    echo PreReleaseLabel: $(PRERELEASELABEL)
    echo PreReleaseNumber: $(PRERELEASENUMBER)
    echo WeightedPreReleaseNumber: $(WEIGHTEDPRERELEASENUMBER)
    echo BuildMetaData: $(BUILDMETADATA)
    echo BuildMetaDataPadded: $(BUILDMETADATAPADDED)
    echo FullBuildMetaData: $(FULLBUILDMETADATA)
    echo MajorMinorPatch: $(MAJORMINORPATCH)
    echo SemVer: $(SEMVER)
    echo LegacySemVer: $(LEGACYSEMVER)
    echo LegacySemVerPadded: $(LEGACYSEMVERPADDED)
    echo AssemblySemVer: $(ASSEMBLYSEMVER)
    echo AssemblySemFileVer: $(ASSEMBLYSEMFILEVER)
    echo InformationalVersion: $(INFORMATIONALVERSION)
    echo BranchName: $(BRANCHNAME)
    echo Sha: $(SHA)
    echo ShortSha: $(SHORTSHA)
    echo NuGetVersionV2: $(NUGETVERSIONV2)
    echo NuGetVersion: $(NUGETVERSION)
    echo NuGetPreReleaseTagV2: $(NUGETPRERELEASETAGV2)
    echo NuGetPreReleaseTag: $(NUGETPRERELEASETAG)
    echo VersionSourceSha: $(VERSIONSOURCESHA)
    echo CommitsSinceVersionSource: $(COMMITSSINCEVERSIONSOURCE)
    echo CommitsSinceVersionSourcePadded: $(COMMITSSINCEVERSIONSOURCEPADDED)
    echo CommitDate: $(COMMITDATE)
```
</details>

Another issue is that variables (e.g. `Major`) are set to empty value instead of `0` by the task.
![image](https://user-images.githubusercontent.com/25345228/94663609-2463ab00-030a-11eb-9873-61609804e2a5.png)
![image](https://user-images.githubusercontent.com/25345228/94663789-5ecd4800-030a-11eb-92cb-3c8847a29ebf.png)

But using fallback values for numeric variables can help with that (depending on where they are used).
e.g. `echo Major: ${MAJOR:-0}`

<details>
<summary>Config (with fallbacks to `0` for numeric)</summary>

```
steps:
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.1.3'
- task: gitversion/execute@0
  displayName: Use GitVersion
- script: |
    echo FullSemVer: $(FULLSEMVER)
    echo ##vso[build.updatebuildnumber]$(FULLSEMVER)
    echo Major: ${MAJOR:-0}
    echo Minor: ${MINOR:-0}
    echo Patch: ${PATCH:-0}
    echo PreReleaseTag: $(PRERELEASETAG)
    echo PreReleaseTagWithDash: $(PRERELEASETAGWITHDASH)
    echo PreReleaseLabel: $(PRERELEASELABEL)
    echo PreReleaseNumber: ${PRERELEASENUMBER:-0}
    echo WeightedPreReleaseNumber: ${WEIGHTEDPRERELEASENUMBER:-0}
    echo BuildMetaData: ${BUILDMETADATA:-0}
    echo BuildMetaDataPadded: $(BUILDMETADATAPADDED)
    echo FullBuildMetaData: $(FULLBUILDMETADATA)
    echo MajorMinorPatch: $(MAJORMINORPATCH)
    echo SemVer: $(SEMVER)
    echo LegacySemVer: $(LEGACYSEMVER)
    echo LegacySemVerPadded: $(LEGACYSEMVERPADDED)
    echo AssemblySemVer: $(ASSEMBLYSEMVER)
    echo AssemblySemFileVer: $(ASSEMBLYSEMFILEVER)
    echo InformationalVersion: $(INFORMATIONALVERSION)
    echo BranchName: $(BRANCHNAME)
    echo Sha: $(SHA)
    echo ShortSha: $(SHORTSHA)
    echo NuGetVersionV2: $(NUGETVERSIONV2)
    echo NuGetVersion: $(NUGETVERSION)
    echo NuGetPreReleaseTagV2: $(NUGETPRERELEASETAGV2)
    echo NuGetPreReleaseTag: $(NUGETPRERELEASETAG)
    echo VersionSourceSha: $(VERSIONSOURCESHA)
    echo CommitsSinceVersionSource: ${COMMITSSINCEVERSIONSOURCE:-0}
    echo CommitsSinceVersionSourcePadded: $(COMMITSSINCEVERSIONSOURCEPADDED)
    echo CommitDate: $(COMMITDATE)
```
</details>

**Comment by chris-codeflow** [comment]
The `steps...` syntax is invalid in Azure Pipelines, so all of the echo commands in the script using that syntax will result in an error.

GitVersion outputs both job-scoped (which can be accessed in subsequent steps in the same job) and multi-job output variables (which can be accessed in other jobs and stages) using the format `GitVersion.<variable>`.  The following Azure Pipelines YAML is correct:

```yaml
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: Use GitVersion

- script: |
    echo Major: $(GitVersion.Major)
    echo Minor: $(GitVersion.Minor)
    echo Patch: $(GitVersion.Patch)
    echo PreReleaseTag: $(GitVersion.PreReleaseTag)
    echo PreReleaseTagWithDash: $(GitVersion.PreReleaseTagWithDash)
    echo PreReleaseLabel: $(GitVersion.PreReleaseLabel)
    echo PreReleaseNumber: $(GitVersion.PreReleaseNumber)
    echo WeightedPreReleaseNumber: $(GitVersion.WeightedPreReleaseNumber)
    echo BuildMetaData: $(GitVersion.BuildMetaData)
    echo BuildMetaDataPadded: $(GitVersion.BuildMetaDataPadded)
    echo FullBuildMetaData: $(GitVersion.FullBuildMetaData)
    echo MajorMinorPatch: $(GitVersion.MajorMinorPatch)
    echo SemVer: $(GitVersion.SemVer)
    echo LegacySemVer: $(GitVersion.LegacySemVer)
    echo LegacySemVerPadded: $(GitVersion.LegacySemVerPadded)
    echo AssemblySemVer: $(GitVersion.AssemblySemVer)
    echo AssemblySemFileVer: $(GitVersion.AssemblySemFileVer)
    echo FullSemVer: $(GitVersion.FullSemVer)
    echo InformationalVersion: $(GitVersion.InformationalVersion)
    echo BranchName: $(GitVersion.BranchName)
    echo EscapedBranchName: $(GitVersion.EscapedBranchName)
    echo Sha: $(GitVersion.Sha)
    echo ShortSha: $(GitVersion.ShortSha)
    echo NuGetVersionV2: $(GitVersion.NuGetVersionV2)
    echo NuGetVersion: $(GitVersion.NuGetVersion)
    echo NuGetPreReleaseTagV2: $(GitVersion.NuGetPreReleaseTagV2)
    echo NuGetPreReleaseTag: $(GitVersion.NuGetPreReleaseTag)
    echo VersionSourceSha: $(GitVersion.VersionSourceSha)
    echo CommitsSinceVersionSource: $(GitVersion.CommitsSinceVersionSource)
    echo CommitsSinceVersionSourcePadded: $(GitVersion.CommitsSinceVersionSourcePadded)
    echo UncommittedChanges: $(GitVersion.UncommittedChanges)
    echo CommitDate: $(GitVersion.CommitDate)
```

Azure Pipelines creates _environment variables_ from the job-scoped variables of the form `GITVERSION_<ALLCAPSVARIABLE>` which you can also use in the same job.

I will be correcting the example and adding new ones (including how to access the variables in different jobs and stages) to address issue #236.
