### ISSUE TITLE
Deprecated set-env and add-path commands 

### ISSUE THREAD

**Issue by asbjornu** [GitTools/actions#213]
GitHub is [deprecating `set-env` and `add-path` commands](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/), causing the GitVersion action to log the following warning when executed:

>The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/12283/95333611-49799000-08ad-11eb-9360-26a886548522.png">

I'm not sure what the fix is, because we are using `v1.2.6` of `@actions/core` already.

>Action authors who are using the toolkit should update the `@actions/core` package to `v1.2.6` or greater to get the updated `addPath` and `exportVariable` functions.

**Comment by asbjornu** [comment]
I was using version `0.9.2` of `gittools/actions/gitversion/execute`. Upgrading to `0.9.4` fixed the problem. 🤦‍♂️

**Comment by JohnNeville** [comment]
I am not sure if it is something in our specific environment but we are actually getting the same error despite using v0.9.4 for both the setup and execute action. 

![image](https://user-images.githubusercontent.com/11984108/95378470-f950fc80-08b1-11eb-837a-09b446e6dd69.png)

**Comment by danstis** [comment]
I am also still getting these errors on v0.9.4

**Comment by asbjornu** [comment]
This was fixed in GitTools/GitVersion#2422.

**Comment by willemduncan** [comment]
The warning still shows up, using the following config:
```yml
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.4
        with:
          versionSpec: 5.x
```

Which results in the following output:
```
Run gittools/actions/gitversion/setup@v0.9.4
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

--------------------------
Installing GitVersion.Tool version 5.x
--------------------------
Command: dotnet tool install GitVersion.Tool --tool-path /home/runner/work/_temp/cf986213-77c5-427f-ae47-e5316b83bdd5 --version 5.5.0
/usr/bin/dotnet tool install GitVersion.Tool --tool-path /home/runner/work/_temp/cf986213-77c5-427f-ae47-e5316b83bdd5 --version 5.5.0

... snipped for brevity ...

You can invoke the tool using the following command: dotnet-gitversion
Tool 'gitversion.tool' (version '5.5.0') was successfully installed.
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/```

Running the latest script version `0.9.4` and it loads the patched `5.5.0` release.

**Comment by asbjornu** [comment]
That's weird, @willemduncan. Thoughts,  @danielmarbach?

**Comment by arturcic** [comment]
@asbjornu  this could be because we use this for GH actions https://github.com/GitTools/actions/blob/02ac2511c1395a56eaaba8fc7fb3535241b3d898/src/agent/github/build-agent.ts#L171 that calls this https://github.com/actions/toolkit/blob/0759cdc2309acfd91b6503597dcfa02a3cee99d0/packages/core/src/core.ts#L51

**Comment by asbjornu** [comment]
Aha, nice find @arturcic. Perhaps an upgrade of the actions toolkit is enough to get rid of the problem, then?

**Comment by arturcic** [comment]
Could be

**Comment by danielmarbach** [comment]
Yes, anything that uses `set-env` will trigger this warning, unfortunately.

**Comment by asbjornu** [comment]
A bit strange that Dependabot hasn't submittet a PR with an upgrade that fixed this, then. Hm.

**Comment by jameswoodley** [comment]
Not sure if helpful, but just wanted to call out we're still seeing this on v0.9.4

```
- name: Fetch all history for all tags and branches
  run: git fetch --prune --unshallow
- name: Install GitVersion
  uses: gittools/actions/gitversion/setup@v0.9.4
  with:
    versionSpec: '5.3.x'
- name: Use GitVersion
  id: gitversion # step id used as reference for output values
  uses: gittools/actions/gitversion/execute@v0.9.4
```
