### ISSUE TITLE
gitversion/execute fails with error: The `set-env` command is disabled.

### ISSUE THREAD

**Issue by MarkusHorstmann** [GitTools/actions#255]
Workaround is to set the indicated environment variable:

    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.6
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true # workaround for https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ until the execute action is updated

Used in https://github.com/TRUMPF-IoT/C-DEngine/blob/master/.github/workflows/dotnetcore.yml

**Comment by johnc-ftl** [comment]
It looks like this was fixed in 0.9.6. I just ran a github build successfully after upgrading to 0.9.6.

```yaml
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.6
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@v0.9.6
```
