### ISSUE TITLE
gitversion/setup doesn't work in GH Actions with Ubuntu 20.04

### ISSUE THREAD

**Issue by ASarco** [GitTools/actions#347]
Since today, Github Actions started using Ubuntu 20.04 for its images.
When trying to run gitversion/setup 0.9.9 we get:

`
Command: dotnet tool install GitVersion.Tool --tool-path /tmp/github/_temp/7d617446-79ec-41c3-a31f-064119cf69ec --version 5.6.6
Error: Unable to locate executable file: dotnet. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
`

A workaround seem to be downgrading to 18.04 by using
`runs-on: ubuntu-18.04`

But it would be nice if there is a better solution.

**Comment by connorwyatt** [comment]
I'm seeing this exact issue too, I've pinned the ubuntu version as the OP suggested as a temporary solution as well

**Comment by BinToss** [comment]
Try using https://github.com/marketplace/actions/setup-nuget-exe-for-use-with-actions before the GitTools action.

**Comment by KairaMiu** [comment]
Same issue here. 

Thanks @ASarco for the workaround.

**Comment by jemshit** [comment]
For macos arm64, [this](https://stackoverflow.com/a/65625154/3736955) helped

**Comment by devenes** [comment]
Hi everyone, I just wanted to let you know that I tested `gitversion/setup` with Ubuntu 20.04 and it appears to be working now. It's possible that the issue has been resolved since it was first reported.

As an example, I used the following code snippet to install GitVersion on Ubuntu 20.04 in a GitHub Actions workflow:

```yaml
name: Git Version Demo

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.5.0"
```
This code successfully installed GitVersion on Ubuntu 20.04 and ran without any issues.

If anyone else has encountered this issue recently, I would encourage you to try again with the latest version of the tool and let us know if you're still experiencing any problems.

Based on my testing, I believe this issue can now be closed. Thanks for bringing it to our attention!
