### ISSUE TITLE
AssemblyVersionAttribute not added correctly for WPF projects

### ISSUE THREAD

**Issue by ghostelet** [GitTools/actions#375]
Hi,

I use the following configuration in my Azure DevOps yml build file:

```
- task: gitversion/execute@0
  displayName: GitVersion
  inputs:
    useConfigFile: true
    configFilePath: 'GitVersion.yml'
    updateAssemblyInfo: true
    updateAssemblyInfoFileName: '$(Build.SourcesDirectory)/path/to/my/AssemblyInfo.cs'
```

When the task executes it seems `AssemblyVersionAttribute` and the likes (`AssemblyFileVersionAttribute`, etc...) are correctly added BUT without specifying the full namespace. I guess the generated output is something like this:

`[assembly: AssemblyVersionAttribute("1.0.0.0")]`

instead of

`[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]`

This causes the subsequent Build task to fail with the error:

> The type or namespace name 'AssemblyVersionAttribute' could not be found (are you missing a using directive or an assembly reference?)

To workaround it, I have to manually add:

`using System.Reflection;`

on top of my `AssemblyInfo.cs` file but it's not convenient because it is actually not used in my Visual Studio solution and regularly gets cleaned up causing the nexrt build to fail.

This issue occurs only when building WPF application and WPF class libraries. using .NET Core 3.1 or .NET 5.0 These types of projects automatically create a file `AssemblyInfo.cs` in the root folder of the project to input attributes related to `ThemeInfo`. The issue does not occur in my "normal" .NET Core and .NET 5.0 class libraries. As a matter of fact  in these later ones, I don't even have to specify an `updateAssemblyInfoFileName` property in gitversion/execute@0 task.

Thanks
