### ISSUE TITLE
gitversion doesn't work with dotnet core 3.1

### ISSUE THREAD

**Issue by dnperfors** [GitTools/actions#42]
On our project we use dotnet core 3.1, but when running gitversion in our pipeline it fails since it wants 2.1

azurepipeline.yaml
```
steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Install .NET Core sdk 3.1.100'
    inputs:
      version: 3.1.100

  - task: gittools.gittools.setup-gitversion-task.gitversion/setup@0
    displayName: gitversion/setup
    inputs:
      versionSpec: 5.1.x

  - task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
    displayName: gitversion/execute
    inputs:
      useConfigFile: true
      configFilePath: GitVersion.yml
```

Output:
```
Command: dotnet-gitversion /workspace/2/s /output json /config /workspace/2/s/GitVersion.yml 
[command]/workspace/_tool/GitVersion.Tool/5.1.3/x64/dotnet-gitversion /workspace/2/s /output json /config /workspace/2/s/GitVersion.yml undefined
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.0 at [/workspace/_tool/dncs/3.1.100/x64/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=ubuntu.18.04-x64
##[error]SyntaxError: Unexpected end of JSON input
```

Workaround is to install 2.1 as well, but I'd rather not do that :)
