### ISSUE TITLE
Cannot find the .git directory with GitHub Workflow

### ISSUE THREAD

**Issue by ttasharski73** [GitTools/actions#469]
Command: dotnet-gitversion D:/actions-runner/_work/demoapp/demoapp /output json /output buildserver /config GitVersion.yml
D:\actions-runner\_work\_tool\GitVersion.Tool\5.6.10\x64\dotnet-gitversion.exe D:/actions-runner/_work/demoapp/demoapp /output json /output buildserver /config GitVersion.yml
INFO [07/07/21 10:30:05:23] Working directory: D:/actions-runner/_work/demoapp/demoapp
Cannot find the .git directory
INFO [07/07/21 10:30:05:26] Done writing 
Error: Error: The process 'D:\actions-runner\_work\_tool\GitVersion.Tool\5.6.10\x64\dotnet-gitversion.exe' failed with exit code 1

Has anyone seen this error before? I am stuck

**Comment by fabio-lonegro-deltatre** [comment]
Hey @ttasharski73 I had the same issue, my workaround is to use checkout v1 instead of v2>
```yaml
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
```
