### ISSUE TITLE
File not found: 'd:\a\_actions\gittools\actions\v0.9.1\dist/github/setup/index.js'

### ISSUE THREAD

**Issue by riverar** [GitTools/actions#47]
GitHub Actions workflow contains:

```
- name: Install GitVersion
  uses: gittools/actions@v0.9.1
  with:
    versionSpec: '5.1.x'
    includePrerelease: false
```

Output:
```
Run gittools/actions@v0.9.1
##[error]File not found: 'd:\a\_actions\gittools\actions\v0.9.1\dist/github/setup/index.js'
```
