### ISSUE TITLE
[GitVersion] increment PreReleaseNumber for each branch separately

### ISSUE THREAD

**Issue by zs-dima** [GitTools/actions#538]
GitVersion increment PreReleaseNumber for each branch separately. 
Is there any way to increment PreReleaseNumber or CommitsSinceVersionSource continually instead?
I tried to use github.run_number instead, but it increment for each workflow separately ...
I using GitHub actions with GitVersion 5.x

default settings + mode=Mainline

```
runs:
  using: "composite"
  steps:
    - uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: ${{ inputs.gitversion-version }}
    - id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        additionalArguments: '/overrideconfig mode=Mainline'
```
