### ISSUE TITLE
[enhancement] Ability to force download of the latest GitVersion tooling in gitversion/setup@0 Azure DevOps task

### ISSUE THREAD

**Issue by cytron201** [GitTools/actions#563]
The gitversion/setup@0 pipeline task will fetch a defined version of the GitVersion tool if one is not found on the server. However it will also use whatever version it finds in the tool cache that matches the versionSpec, even if a newer version has been released.

For example: in the situation where GitVersion has previously downloaded 5.5.1, this task will continue to use that for all subsequent builds, even though 5.7.0 has been released:

```
  - name: "GitVersionVersion"
    value: "5.x"
....
          - task: gitversion/setup@0
            displayName: "Use Gitversion $(GitVersionVersion)"
            inputs:
              versionSpec: "$(GitVersionVersion)"
```

Ideally, it'd check if a newer matching version exists and fetch that, either automatically or via an optional bool. Much like the "Use dotnet" pipeline task behaves.
