### ISSUE TITLE
GitVersion.yml is not correctly set as default if useConfigFile == true

### ISSUE THREAD

**Issue by luke-barnett** [GitTools/actions#570]
As per examples: https://github.com/GitTools/actions/blob/main/docs/examples/azure/gitversion/execute/usage-examples.md

We should be able to set:

```
- task: gitversion/execute@0
  displayName: Determine Version
  inputs:
    useConfigFile: true
```

as an equivalent to:

```
- task: gitversion/execute@0
  displayName: Determine Version
  inputs:
    useConfigFile: true
    configFilePath: 'GitVersion.yml'
```

However, the default doesn't seem to be set, and you need to explicitly set configFilePath.
