### ISSUE TITLE
GitVersion.SemVer: command not found

### ISSUE THREAD

**Issue by djbreen7** [GitTools/actions#61]
The code sample below produces the error `GitVersion.SemVer: command not found`

```yaml
  - task: UseGitVersion@5
    inputs:
      versionSpec: '5.x'

  ...

  - script: npm version $(GitVersion.SemVer) --no-git-tag-version
    displayName: 'NPM Version'
```

**Workaround**
Based on other issues, rolling back to `5.1.2` fixes the issue for me.
