### ISSUE TITLE
If you use UseDotnet task before GitVesion you will get error

### ISSUE THREAD

**Issue by pherbel** [GitTools/actions#65]
If you use UseDotnet task before GitVesion you will get error. (UseGitVersion and GitTools tasks are the same)

```
- task: UseDotNet@2
   displayName: ".NET Core 3.1.x"
   inputs:
     packageType: 'sdk'
     version: '3.1.x'
 - task: gitversion/setup@0
   inputs:
     versionSpec: '5.x'
 - task: gitversion/execute@0
   inputs:
     useConfigFile: true
     configFilePath: 'GitVersion.yml'
     additionalArguments: ''
```
You will get this error:
`##[error]Error: EINVAL: invalid argument, readlink '/opt/hostedtoolcache/dotnet/dotnet'`

**Comment by gojanpaolo** [comment]
Using `UseDotNet` before `UseGitVersion` is working fine on our end.

```yml
steps:

- task: UseDotNet@2
  inputs:
    version: '3.x'

- task: UseGitVersion@5
  name: UseGitVersion
  inputs:
    versionSpec: '5.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    configuration: 'Release'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'UseGitVersion.GitVersion.SemVer'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.nuspec'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'UseGitVersion.GitVersion.SemVer'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    publishVstsFeed: '...'
```
