### ISSUE TITLE
Tag is used according to triggering branch, not from the target in Azure Devops

### ISSUE THREAD

**Issue by Echarnus** [GitTools/actions#798]
Both pipelines and gitversion are stored within the pipelines repository 

![image](https://user-images.githubusercontent.com/9265969/220659185-42f646d0-ba12-43ee-9ed8-41c85544c8ed.png)

This is our GitVersion.yml 

```
mode: Mainline
branches:
  main:
    regex: ^main$|^master$
    increment: Minor
    is-mainline: true
  develop:
  # Match nothing - Unused
    regex: ^\b$
  release:
    regex: ^release?[/-]
    increment: None
  feature:
    regex: ^feature[/-]
    tag: 'prerelease'
    increment: Minor
    is-source-branch-for: [ 'main' ]
  pull-request:
    # Match nothing - Unused
    regex: ^\b$
  hotfix:
    regex: ^fix[/-]
    tag: 'hotfix'
    increment: Patch
    is-source-branch-for: [ 'main', 'release' ]
  support:
    # Match nothing - Unused
    regex: ^\b$
ignore:
  sha: []
merge-message-formats: {}
```
Our pipeline

```
parameters:
  - name: projectPath
    type: string

steps:
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: "5.10.x"
- task: gitversion/execute@0
  displayName: Use GitVersion
  name: Version # the step MUST be named to access its output variables in another job.
  inputs: 
    useConfigFile: true
    targetPath: ${{parameters.projectPath}}
    configFilePath: $(Build.SourcesDirectory)/pipelines/gitversion.yml
```

Since I have chosen the branch fix/fixing-versioning as a target, it should have become 1.5.1-hotfix.1. When however the build is triggered via the pull request pipeline and because of a change in the fix/fixing-versioning branch, the version however is correct.
