### ISSUE TITLE
SemVer calculates as previous CommitsSinceVersionSource + current CommitsSinceVersionSource

### ISSUE THREAD

**Issue by Snuffsis** [GitTools/actions#843]
I am using this to get the SemVer when action is being triggered (on push, or in my case when a pull request is merged into the specified branches)
```yml
 calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Gittools
      uses: GitTools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
```

But when It runs the first time, it gets the right amount of commits since last in the variable "CommitsSinceVersionSource", or in "SemVer"
example:
![bild](https://user-images.githubusercontent.com/8822958/229991741-67193b34-79c3-4535-9dc8-2164380f35d1.png)

But then, I made two more commits to fix an error and pushed it and merged it, and it seems to take the previous number, and then add the current number to it, making it end up as 18 next time. while the variable "CommitsSinceVersionSource" has the correct number of "10"
![bild](https://user-images.githubusercontent.com/8822958/229993646-b0fb8c48-75cb-4051-88a0-4b12c3fcb5ff.png)

Is this intentional, or some weird bug because of my other step where I am creating a new tag and a release maybe?
