### ISSUE TITLE
Execute GitVersion Task customizable BuildNumber output

### ISSUE THREAD

**Issue by namtab00** [GitTools/actions#844]
[Documentation](https://github.com/GitTools/actions/blob/main/docs/examples/azure/gitversion/execute/usage-examples.md#outputs) for the _Azure DevOps_ **Execute GitVersion Task** states

> GitVersion also automatically updates the pre-defined Build variable _Build.BuildNumber_.

This does seem to work but there's no way to control what output is used, it always uses `GitVersion_SemVer`.

I've tried setting _BuildNumber_ to something else by using a subsequent task, but to no avail...

```yaml
- task: gitversion/setup@0
      displayName: Install GitVersion
      inputs:
        versionSpec: '5.x'
        preferLatestVersion: true

- task: gitversion/execute@0
  name: ComputeVersion
  displayName: Compute version
  inputs:
    additionalArguments: '/verbosity Verbose' # /showConfig to view GitVersion config

- script: echo %Action%%BuildVersion%
  displayName: 'Updating build number to GitVersion_MajorMinorPatch'
  env:
    Action: '##vso[build.updatebuildnumber]'
    BuildVersion: '$(GitVersion_MajorMinorPatch)'
```

Am I missing something blatantly obvious?

**Comment by arturcic** [comment]
@namtab00 you have to set the `##vso[build.updatebuildnumber]` in a script and not as env

something like:
```yml
- task: gitversion/execute@0
  name:  version # id to later be referenced 
  displayName: Compute version
  inputs:
    additionalArguments: '/verbosity Verbose' # /showConfig to view GitVersion config

- script: echo '##vso[build.updatebuildnumber]$(version.GitVersion_MajorMinorPatch)'
  displayName: 'Updating build number to GitVersion_MajorMinorPatch'
```
