### ISSUE TITLE
Execute GitVersion Task 0.10.2 cross-stage output variables

### ISSUE THREAD

**Issue by namtab00** [GitTools/actions#845]
I've tried any possible incantation of what is provided in [Example 10](https://github.com/GitTools/actions/blob/main/docs/examples/azure/gitversion/execute/usage-examples.md#example-10).

I've not, for the life of me, managed to read an output variable from the Execute task output.

[Documentation](https://github.com/GitTools/actions/blob/main/docs/examples/azure/gitversion/execute/usage-examples.md#outputs) states:
> The multi-job output variables can be accessed across **jobs and stages**, in both conditions **and variables**

This is what I've tried, including the dirty workaround I've resorted to.

```yaml
variables:
- name: workaroundVar
  value: "COMPUTED_DURING_BUILD"

stages:
- stage: Stage1
  jobs:
  - job: Stage1Job1
    steps:
    - checkout: self
      fetchDepth: 0
      clean: true

    - task: gitversion/setup@0
      displayName: Install GitVersion
      inputs:
        versionSpec: '5.x'
        preferLatestVersion: true

    - task: gitversion/execute@0
      name: ComputeVersionTask
      inputs:
        additionalArguments: '/verbosity Verbose'

    - task: PowerShell@2
      name: WorkaroundViaCustomVariableTask
      inputs:
        targetType: inline
        script: |
          $varValue = $env:GITVERSION_MAJORMINORPATCH
          Write-Host "##vso[task.setvariable variable=workaroundVar;isOutput=true]$varValue"

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: env | sort

    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(sourceRepoName)
        command: push
        tags: $(workaroundVar)    # <<<<<<<<<< both $(GitVersion_MajorMinorPatch) and $(ComputeVersionTask.GitVersion_MajorMinorPatch) is empty here !!!!!

- stage: Stage2
  dependsOn: Stage1
  variables:
    newCustomVar: $[ stageDependencies.Stage1.Stage1Job1.outputs['ComputeVersionTask.GitVersion_MajorMinorPatch'] ] # <<<< evaluated as empty !!!!!
    workaroundVar: $[ stageDependencies.Stage1.Stage1Job1.outputs['WorkaroundViaCustomVariableTask.customVar'] ] # <<< this works...
  jobs:
  - job: Stage2Job1
    variables:
      newCustomVar: $[ stageDependencies.Stage1.Stage1Job1.outputs['ComputeVersionTask.GitVersion_MajorMinorPatch'] ] # <<<< evaluated as empty !!!!!
      workaroundVar: $[ stageDependencies.Stage1.Stage1Job1.outputs['WorkaroundViaCustomVariableTask.customVar'] ] # <<< this works...
    steps:
    - checkout: none

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: env | sort
```

Tasks run in a pool on _ubuntu-latest_.

what
