### ISSUE TITLE
Examples 5 & 6 output variables incorrect for Azure DevOps

### ISSUE THREAD

**Issue by bartlannoeye** [GitTools/actions#849]
Similar to #845, I spent whole afternoon trying to make examples 5 and 6 work on Azure DevOps in a YAML pipeline. I changed all output variables to use GitVersion. rather than _ and it works. Notice that the other 3 options didn't work either.

```
- task: gitversion/setup@0
  displayName: 'Install GitTools'
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  name: version
  displayName: 'Calculate SemVer'

-  script: |
    echo "Major: $(GitVersion.Major)"
    echo "Minor: $(GitVersion.Minor)"
    echo "Patch: $(GitVersion.Patch)"
    echo "PreReleaseTag: $(GitVersion.PreReleaseTag)"
    echo "PreReleaseTagWithDash: $(GitVersion.PreReleaseTagWithDash)"
    echo "PreReleaseLabel: $(GitVersion.PreReleaseLabel)"
    echo "PreReleaseNumber: $(GitVersion.PreReleaseNumber)"
    echo "WeightedPreReleaseNumber: $(GitVersion.WeightedPreReleaseNumber)"
    echo "BuildMetaData: $(GitVersion.BuildMetaData)"
    echo "BuildMetaDataPadded: $(GitVersion.BuildMetaDataPadded)"
    echo "FullBuildMetaData: $(GitVersion.FullBuildMetaData)"
    echo "MajorMinorPatch: $(GitVersion.MajorMinorPatch)"
    echo "SemVer: $(GitVersion.SemVer)"
    echo "LegacySemVer: $(GitVersion.LegacySemVer)"
    echo "LegacySemVerPadded: $(GitVersion.LegacySemVerPadded)"
    echo "AssemblySemVer: $(GitVersion.AssemblySemVer)"
    echo "AssemblySemFileVer: $(GitVersion.AssemblySemFileVer)"
    echo "FullSemVer: $(GitVersion.FullSemVer)"
    echo "InformationalVersion: $(GitVersion.InformationalVersion)"
    echo "BranchName: $(GitVersion.BranchName)"
    echo "EscapedBranchName: $(GitVersion.EscapedBranchName)"
    echo "Sha: $(GitVersion.Sha)"
    echo "ShortSha: $(GitVersion.ShortSha)"
    echo "NuGetVersionV2: $(GitVersion.NuGetVersionV2)"
    echo "NuGetVersion: $(GitVersion.NuGetVersion)"
    echo "NuGetPreReleaseTagV2: $(GitVersion.NuGetPreReleaseTagV2)"
    echo "NuGetPreReleaseTag: $(GitVersion.NuGetPreReleaseTag)"
    echo "VersionSourceSha: $(GitVersion.VersionSourceSha)"
    echo "CommitsSinceVersionSource: $(GitVersion.CommitsSinceVersionSource)"
    echo "CommitsSinceVersionSourcePadded: $(GitVersion.CommitsSinceVersionSourcePadded)"
    echo "UncommittedChanges: $(GitVersion.UncommittedChanges)"
    echo "CommitDate: $(GitVersion.CommitDate)"
```

**Comment by bartlannoeye** [comment]
Stale docs at https://gitversion.net/docs/reference/build-servers/azure-devops don't help either in troubleshooting.

**Comment by arturcic** [comment]
we have a test repository https://github.com/GitTools/actions-test. I will try to add the samples from the examples into the GitHub actions and AzureDevops pipelines so that we can validate the examples as well

**Comment by philipwolfe** [comment]
@bartlannoeye Thank you for posting this at just the right time.  I have been trying things for hours and this is what I needed.  And if any of these keywords will help people find this: 
devops pipeline reference task by name
devops pipeline reference task property

Here is my test pipeline:
```yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  name: version # id to later be referenced
  displayName: Determine Version

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Sha: $(GitVersion.sha)"
```

**Comment by dazinator** [comment]
Can confirm same issue, after some (plenty) of experimentation here is a working example of running gitversion in a job in stage 1, then accessing a version variable in a `deployment` job in stage 2.

```yaml

stages:

- stage: VersionStage
  jobs: 
  - job: 'VersionJob' 
    steps:     
    # this is required for gitversion
    - checkout: self
      fetchDepth: 0      

    - task: gitversion/setup@0
      displayName: Install GitVersion
      inputs:
        versionSpec: '5.11.1'

    - task: gitversion/execute@0     
      displayName: Determine Version
      name: VersionTask         

- stage: DeployStage
  displayName: "Deploy"
  condition: |
    and(
      succeeded('VersionStage'), 
      eq(${{ parameters.deploy }}, true)
    )
  dependsOn: VersionStage

  jobs:    

  - deployment: BuildAgent
    displayName: Deploy
    environment: 
      name: YourEnvName
      resourceType: VirtualMachine        
    
    variables:    
    - name: semver
       value: $[ stageDependencies.VersionStage.VersionJob.outputs['VersionTask.GitVersion.SemVer'] ]
```

i.e use a `.` rather than `_`  for accessing gitversion variables.
