### ISSUE TITLE
Fetch and Create Reflog don't work for private repositories (Unauthorized)

### ISSUE THREAD

**Issue by bofirial** [GitTools/actions#9]
I found that the directions as documented don't work for private repositories.

When one creates an action in a private repository following the instructions,  they'll find that the action fails or hangs when it tries to run 'git fetch --tags'.  With an ubuntu action the error reads: 'fatal: could not read Username for 'https://github.com': No such device or address'.  With a windows action the action hangs after it opens credential manager.

It appears that the [actions/checkout](https://github.com/actions/checkout) action resets git configuration after checkout so the credentials aren't available to the 'git fetch --tags' and 'git branch --create-reflog master origin/master' commands.  https://github.com/actions/checkout/blob/5881116d181dc80f3ed5f395296a5579ee6fc6a4/src/git-source-provider.ts#L146

I recommend adding another line to the 'Fetch tags and master for GitVersion' step in the documentation to add credentials for private repositories.  The following command is working well for me:
```yaml
git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
```

```yaml
    steps:
    - name: Checkout
    uses: actions/checkout@v1
    - name: Fetch tags and master for GitVersion
    run: |          
        git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} # creds needed for private repos
        git fetch --tags
        git branch --create-reflog master origin/master
```
